#!/usr/bin/bash
#***************************************************************************
#               ____   ___  ____   ____       _   __   __                  *
#              |  _ \ |_ _|/ ___| |  _ \     / \  \ \ / /                  *
#              | | | | | | \___ \ | |_) |   / _ \  \ V /                   *
#              | |_| | | |  ___) ||  _ <   / ___ \  | |                    *
#              |____/ |___||____/ |_| \_\ /_/   \_\ |_|   VERSION 1.       *
#                                                                          *
#  +-----------+---------------------------------------------------------+ *
#  |  File     | client_p                                                | *
#  +-----------+---------------------------------------------------------+ *
#  |  Version  | 1                                                       | *
#  +-----------+---------------------------------------------------------+ *
#  |  Year     | 2012                                                    | *
#  +-----------+---------------------------------------------------------+ *
#  | Authors   | Afsaneh Mohammadzaheri <afsaneh.mohamadzaheri@gmail.com>| *
#  |           | Hossein Sadeghi <sadeghi@um.ac.ir>                      | *
#  |           | Keyvan Hosseini <k-hosseini@um.ac.ir>                   | *
#  |           | Mahdi Navazandeh <m.navazandeh@gmail.com>               | *
#  +-----------+---------------------------------------------------------+ *
#  |  Copyright (c) 2012 The DISRAY Authors. All rights reserved.        | *
#  +---------------------------------------------------------------------+ *
#  |  DISRAY : A Distributed Ray tracing by Map-Reduce.                  | *
#  |  Make sure the input(source) is set.                                | *
#  +------------------------------------------------------------------ --+ *
#                                                                          *
#***************************************************************************



#mkdir ~/DISRAY
cat ~/DISRAY/config/.startTxt




#=========env.py=================
echo 'export PATH=~/DISRAY/bin:$PATH' >> ~/.bashrc
echo 'export PATH=~/DISRAY:$PATH' >> ~/.bashrc
source ~/.bashrc

echo 'import os' > ~/DISRAY/lib/env.py
echo 'home_dir=os.getenv("HOME")' >> ~/DISRAY/lib/env.py
echo 'DISRAY_HOME_path=home_dir+"/DISRAY"' >> ~/DISRAY/lib/env.py
echo 'DISRAY_server_cfg_path=home_dir+"/DISRAY/config/server.cfg"' >> ~/DISRAY/lib/env.py
echo 'DISRAY_server_ip_path=home_dir+"/DISRAY/config/server.ip"' >> ~/DISRAY/lib/env.py
echo 'DISRAY_hosts_path=home_dir+"/DISRAY/config/DISRAY.hosts"' >> ~/DISRAY/lib/env.py
echo 'DISRAY_count_path=home_dir+"/DISRAY/config/count"' >> ~/DISRAY/lib/env.py
echo 'DISRAY_id_path=home_dir+"/DISRAY/config/id"' >> ~/DISRAY/lib/env.py
echo 'DISRAY_hosts_ssh_path=home_dir+"/DISRAY/config/.hosts.ssh"' >> ~/DISRAY/lib/env.py
echo 'DISRAY_env_sh_path=home_dir+"/DISRAY/lib/env.sh"' >> ~/DISRAY/lib/env.py
echo 'DISRAY_env_py_path=home_dir+"/DISRAY/lib/env.sh"' >> ~/DISRAY/lib/env.py
echo 'DISRAY_data_path=home_dir+"/DISRAY/data"' >> ~/DISRAY/lib/env.py
echo 'DISRAY_log_path=home_dir+"/DISRAY/log"' >> ~/DISRAY/lib/env.py



#=========env.sh=================
echo "#!/bin/bash" > ~/DISRAY/lib/env.sh
echo 'export PATH=~/DISRAY/bin:$PATH' >> ~/DISRAY/lib/env.sh
echo 'DISRAY_data_path=~/DISRAY/data' >> ~/DISRAY/lib/env.sh
echo 'DISRAY_log_path=~/DISRAY/log' >> ~/DISRAY/lib/env.sh


touch  ~/DISRAY/config/DISRAY.hosts
cat ~/DISRAY/config/DISRAY.hosts

python ~/DISRAY/lib/stdin-ter.py
#chmod a+x stdin-ter.py
#./stdin-ter.py
